spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/serverdb
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true
    show-sql: true