apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
    - name: server
      image: sebastianalexandru/server:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgis-ip-service-2:5432/server_db

---
apiVersion: v1
kind: Service
metadata:
  name: server-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 8080
      targetPort: 8080